### ISSUE TITLE
Install idris2-lsp

### ISSUE THREAD

**Issue by jiwhiz** [joshuanianji/idris-2-docker#12]
The VS Code extension `zjhmale.Idris` is out of date, and for Idris2, we are using [idris2-lsp](https://github.com/idris-community/idris2-lsp), with Visual Studio Code extension [idris2-lsp-vscode](https://github.com/bamboo/idris2-lsp-vscode) 

You can follow the instruction of [Manual Installation](https://github.com/idris-community/idris2-lsp#manual-installation) to install idris2 and idris2-lsp.

I suggest to only work on latest now, ignore idris2 release 0.5.0 and 0.5.1, because there is no idris2-lsp releases.

**Comment by joshuanianji** [comment]
Thanks, I'll split this issue into a few sections.

- #13 
- #15

**Comment by jiwhiz** [comment]
Created a demo project https://github.com/jiwhiz/idris2-hello-world to test idris2-lsp and seems working very well.
