### ISSUE TITLE
Base image missing the Idris2 api package

### ISSUE THREAD

**Issue by kamweti** [joshuanianji/idris-2-docker#63]
### To Reproduce

* base image does `make install` here https://github.com/joshuanianji/idris-2-docker/blob/0cd066eaabfdbe6919f779db3c621ba51c4ab951/base.Dockerfile#L44

* `make install`  installs these packages 
```
install: install-idris2 install-support install-libs
```
https://github.com/idris-lang/Idris2/blob/main/Makefile#L188

* building a library such as [idris2-python](https://github.com/madman-bob/idris2-python) against the base image fails  with
```
required idris2 any but no matching version is installed
```

* the missing dependency is 
```
depends = idris
```
https://github.com/madman-bob/idris2-python/blob/main/idris2-python.ipkg#L5

* this bug can be resolved by installing the api package
```
make install-api
```

### Expected behavior
base image should explicitly install `api`  package

**Comment by joshuanianji** [comment]
Thank for the detailed issue! I'll add a `make install-api

**Comment by joshuanianji** [comment]
Hey @kamweti, merged a PR that should fix it. Can you check that `ghcr.io/joshuanianji/idris-2-docker/base:latest` works for you?

**Comment by kamweti** [comment]
looks good, thanks!

closing the issue now.
