### ISSUE TITLE
The example project not working.

### ISSUE THREAD

**Issue by weihongliang233** [joshuanianji/idris-2-docker#76]
Great work, but please check this issue. 

https://github.com/calebji123/WordleInIdris/issues/3

The example project WordleInIdris seems out-dated. It uses an old vscode extension, throwing error when opening in vscode devcontainer, I think it is not  "ready-to-use" anymore.

**Comment by joshuanianji** [comment]
Hey @weihongliang233, thanks for letting me know! I added an example project in [examples/](https://github.com/joshuanianji/idris-2-docker/tree/main/example) to replace the WordleInIdris project. Let me know if it works for you!

**Comment by weihongliang233** [comment]
Yes I have tried this example. It works well on my machine! 🎉
